bug hide logout button for unauthorized users in ProfileFragment
sozdik-kz/sozdik-android pull request #7
Opened 2020-09-21 11:17 UTC by wilko98

Удалил кнопку выхода для не авторизованных юзеров

2020-09-21 16:19 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +import java.util.*
Wildcards вне закона :) Надо вернуть как было

2020-09-21 16:19 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +    }
Наименование метода не соотвествует функциональности метода, в `onViewCreated` нет ничего кроме настройки вьюх, поэтому не вижу смысла выносить в отдельный метод. Что думаешь?

2020-09-21 16:19 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +        toolbar.menu.findItem(R.id.action_logout).isVisible = AuthUtils.isAuthorized()
Логики не должно быть во `View`, лучше вынести в `Presenter` и оттуда вызывать метод `View::showLogoutButton(isVisible: Boolean)`

2020-09-21 18:40 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +import java.util.*
Авто оптимизация импортов при коммитете )

2020-09-22 04:20 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +    }
Да, там есть настройка 1 вьюхи так что наверное её стоило вынести из метода, а так в общем думаю что удобно листнеры держать в одном методе, просто удобно например если будет расширятся функционал в будущем писать так:
setupViews()
setupListeners()
setupObservers()
setupOtherStaff()...

2020-09-22 04:22 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +    }
Этот экран достаточно простой, предпочтительнее все же заинлайнить

2020-09-22 04:22 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +        toolbar.menu.findItem(R.id.action_logout).isVisible = AuthUtils.isAuthorized()
Посмотрел `Presenter`, там уже есть подписка на профиль, там нужно добавить вызов `View::showLogoutButton(isVisible: Boolean)`

2020-09-25 09:38 UTC, askarsyzdykov requested changes
Won't merge, need changes. :eyes:

2020-09-27 09:47 UTC, wilko98 commented
Окей зафиксапил 😁 @askarsyzdykov

2020-09-27 12:53 UTC, askarsyzdykov requested changes

2020-09-27 12:53 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfilePresenter.kt
> +    fun showLogoutButton(logoutButton: MenuItem) {
так не стоит делать, потому что презентер получает ссылку на объекты View'хи.

2020-09-27 12:53 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> + * Экран профиля. Открывается с [MainFragment] (5 вкладка)
Документация тут лишняя, если изменится код, то придется еще и править комментарии. Давай уберем

2020-09-27 12:53 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/domain/ProfileInteractor.kt
> +    fun isUserAuthorized(): Boolean = AuthUtils.isAuthorized()
у нас уже есть такой метод, по которому можно определить авторизован ли юзер -- `fun getProfileFlow()`, а в презентере есть подписка на этот Flow, там мы проверяем если Profile != null, то вызываем у view::showLogoutButton(true), иначе view::showLogoutButton(false).

Этот метод надо удалить

2020-09-27 15:38 UTC, askarsyzdykov commented
Надо будет подтянуть develop, исправил проблему с сохранением профиля

2020-09-28 04:33 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/presentation/ProfilePresenter.kt
> +    fun showLogoutButton(logoutButton: MenuItem) {
Убрал, думал что вьюхи входят в слой view, а presenter по MVP в отличии от MVVM может менять View поэтому думал что так норм 
Но V(View) как я понял это ViewState(ProfileView) и только его и может менять презентер

2020-09-28 04:34 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/domain/ProfileInteractor.kt
> +    fun isUserAuthorized(): Boolean = AuthUtils.isAuthorized()
 Удалил

2020-09-28 04:35 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> + * Экран профиля. Открывается с [MainFragment] (5 вкладка)
Не согласен, думаю что доки лишними не бывают, при рефакторинге много времени не займет поменять

2020-09-28 04:49 UTC, wilko98 commented on app/src/main/java/kz/sozdik/profile/presentation/ProfilePresenter.kt
> +    fun showLogoutButton(logoutButton: MenuItem) {
И еще MenuItem это не вьюха это интерфейс 🤓  контекст ты с него не получишь, так что не так уж все и плохо

2020-09-28 04:50 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfilePresenter.kt
> +    fun showLogoutButton(logoutButton: MenuItem) {
почитай про MVP)

2020-09-28 04:57 UTC, askarsyzdykov requested changes

2020-09-28 04:57 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> +        toolbar.menu.findItem(R.id.action_logout).isVisible = !isVisible
название метода не соотвествует тому, что тут происходит. давай разделим на 2 метода, как я писал ранее.

> Посмотрел Presenter, там уже есть подписка на профиль, там нужно добавить вызов View::showLogoutButton(isVisible: Boolean)

2020-09-28 04:59 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/profile/presentation/ProfileFragment.kt
> + * Экран профиля. Открывается с [MainFragment] (5 вкладка)
Если таб профиль будет не пятым по счету твоя документация сломается, при рефакторинге другой разработчик может не заметить эту документацию

2020-09-28 05:05 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/base/BaseActivity.kt
> +        item.isVisible = false
для чего эта строка?

2020-09-28 05:09 UTC, wilko98 commented on app/src/main/java/kz/sozdik/base/BaseActivity.kt
> +        item.isVisible = false
Не знаю, исправил

2020-09-28 05:10 UTC, wilko98 commented
Исправил замечания все должно быть норм

2020-09-28 05:19 UTC, askarsyzdykov commented
LGTM, проверю и замержу, если все ок

2020-09-28 06:15 UTC, merged