Bug/navigation back
sozdik-kz/sozdik-android pull request #9
Opened 2020-09-22 16:07 UTC by supersonixxx

2020-09-22 16:12 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/main/MainActivity.kt
> +        if (supportFragmentManager.fragments[0].childFragmentManager.fragments.isNotEmpty()) {
Сложно читается, попробуй упростить

2020-09-23 04:34 UTC, askarsyzdykov requested changes

2020-09-23 04:34 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/main/MainActivity.kt
> +        val mainFragment = supportFragmentManager.fragments.first()
Для надежности лучше искать фрагмент вот так, т.к если логика сортировки фрагментов изменится в SDK, то это может сломать приложение
```suggestion
        val mainFragment = supportFragmentManager.findFragmentById(R.id.container)
```

2020-09-23 04:34 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/main/MainActivity.kt
> +        val bottomNavigationFragments = mainFragment.childFragmentManager.fragments
Тут нарушается отвественность, Активити начинает копаться в дочерних фрагментах mainFragment'a.
Давай перепишем интерфейс вот так  - `BackPressListener::onBackPressed():Boolean`. Тогда мы можем mainFragment привести к этому интерфейсу и вызвать так:
`if ((mainFragment as? BackPressListener) == true) { return }`

а уже в mainFragment просто проверить у bottonNavView активный таб и если это не таб "словарь", то переключить на словарь и вернуть `true`, чтобы активити ничего дальше не делало

2020-09-23 15:12 UTC, askarsyzdykov commented on app/src/main/java/kz/sozdik/main/MainActivity.kt
> +        val mainFragment = supportFragmentManager.findFragmentById(R.id.container)
тут может не mainFragment быть, поэтому давай переименуем в currentFragment или просто fragment, на твой вкус. И мержим, если все работает как надо

2020-09-23 15:13 UTC, supersonixxx commented on app/src/main/java/kz/sozdik/main/MainActivity.kt
> +        val mainFragment = supportFragmentManager.findFragmentById(R.id.container)
Ок)

2020-09-23 15:29 UTC, askarsyzdykov commented
LGTM
@supersonixxx :+1:

2020-09-24 04:37 UTC, merged